import 'package:chamber_of_commerce/pages/user/Company%20_business.dart';
import 'package:chamber_of_commerce/pages/user/Company.dart';
import 'package:chamber_of_commerce/widgets/CompanyDescription.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Logo_Adv_List extends StatefulWidget {
  final int index;

  const Logo_Adv_List({super.key, required this.index});

  @override
  State<Logo_Adv_List> createState() => _Logo_Adv_ListState();
}

class _Logo_Adv_ListState extends State<Logo_Adv_List> {
  List<dynamic> filteredBusinesses = [];
  List<Map<dynamic, dynamic>> uniqueBusinesses = [];
   List<dynamic> data = [];
  bool isLoading = false;
  String errorMessage = '';

  @override
  void initState() {
    super.initState();
    _fetchData();
  }

  Future<void> _fetchData() async {
    try {
      setState(() {
        isLoading = true;
        errorMessage = '';
      });

      // Replace with your actual data fetching logic (using Firebase or other source)
      // final ref = FirebaseDatabase.instance.ref('Query8').once();
      // final snapshot = await ref;
      //  data = snapshot.snapshot.value as List<dynamic>;
      // //  print(snapshot.snapshot.value);
      // //  print(data);
      //  data = data.where((element) => element["logo"]!="").toList();
      ///offline option
      List<Map<dynamic,dynamic>> offLineData = [
   {
    "Account Number": "",
    "Account Name": "EZM TRAD AND INVESTMENT",
    "Profile": "",
    "Tel": "",
    "Mobile": "",
    "Email": "",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "",
    "status": "Not-Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "EZM -Riifo Manufacturing design copy.png",
    "Video": "",
    "logo": "Rilfo.jpg"
  },
  {
    "Account Number": 1508909,
    "Account Name": "REFLECT LOGESTICS AND TRANSPORT PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911244751/0930533385",
    "Email": "reflectlogistics@gmail.com",
    "Website": "http://www.reflectlogistics.com",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "FREIGHT FORWARDERS AND HARBOUR WORKS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Reflect.gif",
    "logo": "Reflect-logistics-logo.jpg"
  },
  {
    "Account Number": 1200539,
    "Account Name": "BELAYNEH KINDE IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911204882",
    "Email": "belaynehkindie@gmail.com",
    "Website": "http://www.belaynehkindie.com",
    "Sector": "IMPORT",
    "Sub-Sector": "EDIBLE OILS & FATS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "BKG (2).gif (1).gif",
    "logo": "BKG.jpg"
  },
  {
    "Account Number": 1200539,
    "Account Name": "BELAYNEH KINDE IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911204882",
    "Email": "belaynehkindie@gmail.com",
    "Website": "http://www.belaynehkindie.com",
    "Sector": "IMPORT",
    "Sub-Sector": "CAR BATTERY",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "BKG (2).gif (1).gif",
    "logo": "BKG.jpg"
  },
  {
    "Account Number": 1200539,
    "Account Name": "BELAYNEH KINDE IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911204882",
    "Email": "belaynehkindie@gmail.com",
    "Website": "http://www.belaynehkindie.com",
    "Sector": "IMPORT",
    "Sub-Sector": "ELECTRICAL AND WIRING ACCESSORIES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "BKG (2).gif (1).gif",
    "logo": "BKG.jpg"
  },
  {
    "Account Number": 1200539,
    "Account Name": "BELAYNEH KINDE IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911204882",
    "Email": "belaynehkindie@gmail.com",
    "Website": "http://www.belaynehkindie.com",
    "Sector": "EXPORT",
    "Sub-Sector": "OILSEEDS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "BKG (2).gif (1).gif",
    "logo": "BKG.jpg"
  },
  {
    "Account Number": "",
    "Account Name": "Ahadu Marble & granite",
    "Profile": "",
    "Tel": "",
    "Mobile": "",
    "Email": "",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "",
    "status": "Not-Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "Ahadu Marble & Granite copy.png",
    "Video": "",
    "logo": "ahadu cons logo.jpg"
  },
  {
    "Account Number": 100361,
    "Account Name": "GIFT REAL ESTATE P.L.C",
    "Profile": "",
    "Tel": "0116188543/6187469/6184379",
    "Mobile": "0945005331/0984656565",
    "Email": "info@giftbusinessgroup.com",
    "Website": "http://www.giftrealestate.com.et",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "REAL ESTATE DEVELOPMENT DISTRIBUTION AND INDUSTRY PARKS DEVELOPMENT INTO LOTS ACTIVITIES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "Gift copy.png",
    "Video": "Gift.gif",
    "logo": "gift-logo.jpg"
  },
  {
    "Account Number": 100361,
    "Account Name": "GIFT REAL ESTATE P.L.C",
    "Profile": "",
    "Tel": "0116188543/6187469/6184379",
    "Mobile": "0945005331/0984656565",
    "Email": "info@giftbusinessgroup.com",
    "Website": "http://www.giftrealestate.com.et",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "FIXED PROPERTY SUBLETTING/RENTING ACTIVITITIES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "Gift copy.png",
    "Video": "Gift.gif",
    "logo": "gift-logo.jpg"
  },
  {
    "Account Number": 1300146,
    "Account Name": "ETHIOPIAN AIRLINES ENTERPRISE",
    "Profile": "",
    "Tel": "0116184471/0118220274",
    "Mobile": "0911214633",
    "Email": "publicrelations@ethiopianairlines.com",
    "Website": "www.ethiopianairlines.com",
    "Sector": "COMMUNITY, SOCIAL AND PERSONAL SERVICES",
    "Sub-Sector": "EDUCATION RELATED SERVICES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ETA.gif",
    "logo": "Ethiopia-Airlines-logo.jpg"
  },
  {
    "Account Number": 1300146,
    "Account Name": "ETHIOPIAN AIRLINES ENTERPRISE",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911214633",
    "Email": "publicrelations@ethiopianairlines.com",
    "Website": "www.ethiopianairlines.com",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "ACTIVITIES OF AIR TRANSPORT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ETA.gif",
    "logo": "Ethiopia-Airlines-logo.jpg"
  },
  {
    "Account Number": "",
    "Account Name": "ABRHAM GOLD MINING MACHINERY",
    "Profile": "",
    "Tel": "",
    "Mobile": "",
    "Email": "",
    "Website": "",
    "Sector": "",
    "Sub-Sector": "",
    "status": "Not-Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "Abraham Gold Mining Machinery copy.png",
    "Video": "Abraham (3).gif (1).gif",
    "logo": "Abraham-logo.jpg"
  },
  {
    "Account Number": "",
    "Account Name": "AFRICA GLOBAL LOGISTICS",
    "Profile": "",
    "Tel": "0115570600/02/03",
    "Mobile": "0910483909",
    "Email": "wongel.yohannes@aglgroup.com",
    "Website": "",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "",
    "status": "Not-Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "AGL-logistics-logo.jpg"
  },
  {
    "Account Number": 1503770,
    "Account Name": "RUHAMA GENERAL FRAME AND GLASS WORK",
    "Profile": "",
    "Tel": "0111718008/0111262814",
    "Mobile": "0930011927/0911695784",
    "Email": "ruhamaglass@gmail.com",
    "Website": "",
    "Sector": "WHOLESALE AND RETAIL",
    "Sub-Sector": "SAND,GRAVEL STONE AND RELATED MATERIALS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "ruhama-logo.jpg"
  },
  {
    "Account Number": 1503770,
    "Account Name": "RUHAMA GENERAL FRAME AND GLASS WORK",
    "Profile": "",
    "Tel": "0111718008/0111262814",
    "Mobile": "0930011927/0911695784",
    "Email": "ruhamaglass@gmail.com",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "NON-METALLIC MINERAL PRODUCTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "ruhama-logo.jpg"
  },
  {
    "Account Number": 1503770,
    "Account Name": "RUHAMA GENERAL FRAME AND GLASS WORK",
    "Profile": "",
    "Tel": "0111718008/0111262814",
    "Mobile": "0930011927/0911695784",
    "Email": "ruhamaglass@gmail.com",
    "Website": "",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "OTHER FREIGHT TRANSPORT BY ROAD",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "ruhama-logo.jpg"
  },
  {
    "Account Number": 1508515,
    "Account Name": "T L TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911923714/0911224838",
    "Email": "tltrading@gmail.com",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "NON METALLIC MINERALS (CLAY,CERAMICS,GYPSUM,LIME AND THEIR PRODUCT)",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "TL.gif",
    "logo": "TL-trading.jpg"
  },
  {
    "Account Number": 1508515,
    "Account Name": "T L TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911923714/0911224838",
    "Email": "tltrading@gmail.com",
    "Website": "",
    "Sector": "CONSTRUCTION",
    "Sub-Sector": "CONSTRUCTION SITE PREPARATION CONTRACTOR",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "TL.gif",
    "logo": "TL-trading.jpg"
  },
  {
    "Account Number": 1508515,
    "Account Name": "T L TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911923714/0911224838",
    "Email": "tltrading@gmail.com",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "NON FERROUS METALS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "TL.gif",
    "logo": "TL-trading.jpg"
  },
  {
    "Account Number": 1502348,
    "Account Name": "KEBROM FOAM AND PLASTIC MANUFACTURING AND DISTRIBU",
    "Profile": "",
    "Tel": "0115516777",
    "Mobile": "0930077338/0911204751",
    "Email": "kebromfoam@gmail.com",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "FOAM AND SPONGE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "kebrom.gif",
    "logo": "KEBROM-FOAM-logo.jpg"
  },
  {
    "Account Number": 1502348,
    "Account Name": "KEBROM FOAM AND PLASTIC MANUFACTURING AND DISTRIBU",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930077338/0911204751",
    "Email": "kebromfoam@gmail.com",
    "Website": "",
    "Sector": "WHOLESALE AND RETAIL",
    "Sub-Sector": "FLORA FOAM",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "kebrom.gif",
    "logo": "KEBROM-FOAM-logo.jpg"
  },
  {
    "Account Number": 1500607,
    "Account Name": "DERBA MIDROC CEMENT PLC",
    "Profile": "",
    "Tel": "0116292534",
    "Mobile": "0911252627",
    "Email": "abdulsemedh@gmail.com",
    "Website": "http://www.derbacement.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "CEMENT, LIME AND PLASTER",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Derba.gif",
    "logo": "derba-cement.jpg"
  },
  {
    "Account Number": 502969,
    "Account Name": "B D O CONSULTING PLC",
    "Profile": "",
    "Tel": "0112757559",
    "Mobile": "0911226759",
    "Email": "million.kibret@bdo-ea.com",
    "Website": "http://www.bdo-ea.com",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "BUSINESS AND MANAGEMENT CONSULTANCY ACTIVITIES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "10.jpg",
    "Video": "bdo.gif",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1509044,
    "Account Name": "BEACON CONSULTING ARCHTECT AND ENGINEERING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911334600",
    "Email": "beaconconsult1@gmail.com",
    "Website": "",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "CONSULTANCY SERVICE ON CONSTRUCTION SERVICE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "beacon trading copy.png",
    "Video": "BEACON (2).gif (1).gif",
    "logo": "beacon.jpg"
  },
  {
    "Account Number": 1509044,
    "Account Name": "BEACON CONSULTING ARCHTECT AND ENGINEERING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911334600",
    "Email": "beaconconsult1@gmail.com",
    "Website": "",
    "Sector": "CONSTRUCTION",
    "Sub-Sector": "WATER WORKS CONTRACTOR",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "beacon trading copy.png",
    "Video": "BEACON (2).gif (1).gif",
    "logo": "beacon.jpg"
  },
  {
    "Account Number": 1505591,
    "Account Name": "MEKODI LOGISTICS PLC",
    "Profile": "",
    "Tel": "0116512800",
    "Mobile": "0911514936/0935986572/0903434445",
    "Email": "mekodilogistics@gmail.com",
    "Website": "http://mekodilogistics.com",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "CUSTOMS CLEARANCE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Mekodi (2).gif.mp4",
    "logo": "mekodi.jpg"
  },
  {
    "Account Number": 1505591,
    "Account Name": "MEKODI LOGISTICS PLC",
    "Profile": "",
    "Tel": "0116512800",
    "Mobile": "0911514936/0935986572/0903434445",
    "Email": "mekodilogistics@gmail.com",
    "Website": "http://mekodilogistics.com",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "FREIGHT FORWARDERS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Mekodi (2).gif.mp5",
    "logo": "mekodi.jpg"
  },
  {
    "Account Number": 1504120,
    "Account Name": "SIM PLASTICS",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911212028",
    "Email": "mamiha2001@yahoo.com",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "PLASTICS RAW MATERIAL",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "sim plastic factory copy.png",
    "Video": "SIM.gif",
    "logo": "SIM-PLASTIC-final.jpg"
  },
  {
    "Account Number": 1504120,
    "Account Name": "SIM PLASTICS",
    "Profile": "",
    "Tel": "0115503715",
    "Mobile": "0911212028",
    "Email": "mamiha2001@yahoo.com",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "SPECIAL PURPOSE MACHINERY",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "sim plastic factory copy.png",
    "Video": "SIM.gif",
    "logo": "SIM-PLASTIC-final.jpg"
  },
  {
    "Account Number": 902395,
    "Account Name": "AMAGA PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911201334",
    "Email": "amaga@ethionet.et",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "BLANKETS, MADE-UP FURNISHING ARTICLES AND STUFFED",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Amaga.gif",
    "logo": "Amaga-logo.jpg"
  },
  {
    "Account Number": 902395,
    "Account Name": "AMAGA PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911201334",
    "Email": "amaga@ethionet.et",
    "Website": "",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "OTHER FREIGHT TRANSPORT BY ROAD",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Amaga.gif",
    "logo": "Amaga-logo.jpg"
  },
  {
    "Account Number": 1200474,
    "Account Name": "UNIVERSAL PLASTIC FACTORY PLC",
    "Profile": "",
    "Tel": "0116463336/0116463555",
    "Mobile": "0911203643/0911415675",
    "Email": "elsa.araya@upfethiopia.com",
    "Website": "http://upfethiopia.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "PLASTIC PRODUCTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "UNIVERSAL PLASTIC FACTORY PLC copy.png",
    "Video": "UFP.gif",
    "logo": "UPF-ethiopia.jpg"
  },
  {
    "Account Number": 1501306,
    "Account Name": "ABAT IMPORT AND EXPORT PLC",
    "Profile": "",
    "Tel": "0111110882",
    "Mobile": "0911228571",
    "Email": "abatexport@gmail.com",
    "Website": "",
    "Sector": "EXPORT",
    "Sub-Sector": "PULSES/CEREALS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "2.jpg",
    "Video": "Abat (3).gif (1).gif",
    "logo": "abat-logo.jpg"
  },
  {
    "Account Number": "",
    "Account Name": "ELTEX TEXTILE AND GARMENT FACTORY/ELIAS TESFAYE H/MARIAM/",
    "Profile": "",
    "Tel": "0114390444",
    "Mobile": 911227515,
    "Email": "eliastknitt22@gmail.com",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "TEXTILES AND GARMENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "eltex.gif",
    "logo": "eltex-textile-and-garment-factory.jpg"
  },
  {
    "Account Number": 303453,
    "Account Name": "HAST ENTERPRISE HORN OF AFRICA STEEL",
    "Profile": "",
    "Tel": "0114665553/55/54",
    "Mobile": "0911238072/0911616604",
    "Email": "haststeel@gmail.com",
    "Website": "http://haststeelenterprise.com",
    "Sector": "IMPORT",
    "Sub-Sector": "IRON AND STEEL",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "hast.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "BLANKETS, MADE-UP FURNISHING ARTICLES AND STUFFED",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "BASIC IRON AND STEEL",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "FOOT WEAR",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "FLOUR AND GRAIN MILL PRODUCTS, INCLUDING RICE AND VEGETABLE MILLING; GRAIN MILL RESIDUES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "DRESSING AND DYEING",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "IMPORT",
    "Sub-Sector": "MACHINERY AND EQUIPMENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "IMPORT",
    "Sub-Sector": "INDUSTRIAL MACHINERY , EQUIPMENT AND ITS SPARE PARTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200240,
    "Account Name": "D.H GEDA TRADE & INDUSTRY PLC",
    "Profile": "",
    "Tel": "0116180641",
    "Mobile": "0911203890",
    "Email": "duguma.million@yahoo.com",
    "Website": "http://www.dhgeda.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "PAINTS, VARNISHES AND SIMILAR COATINGS, PRINTING INK AND MASTICS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "DH geda copy.png",
    "Video": "DH Geda.gif.gif",
    "logo": "DH-LOGO.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0115170000",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "IMPORT",
    "Sub-Sector": "INDUSTRIAL MACHINERY , EQUIPMENT AND ITS SPARE PARTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0118361995",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "IMPORT",
    "Sub-Sector": "IRON AND STEEL",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0118361995",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "IMPORT",
    "Sub-Sector": "CHEMICALS AND CHEMICAL PRODUCTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0118361995",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "IMPORT",
    "Sub-Sector": "COMPUTER AND COMPUTER ACCESSORIES AND PERIPHERAL EQUIPMENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0118361995",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "IMPORT",
    "Sub-Sector": "SPONGES AND FOAM",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0118361995",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "METAL STRUCTURES FROM ALUMINUM",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0118361995",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "IMPORT",
    "Sub-Sector": "AGRICULTURAL MACHINERY AND EQUIPMENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0116635188",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "IMPORT",
    "Sub-Sector": "PLASTICS RAW MATERIAL",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 1200584,
    "Account Name": "B & C ALMUNIUM P.L.C",
    "Profile": "",
    "Tel": "0112781418",
    "Mobile": "0911097228/0911222671",
    "Email": "info@bacalum.com",
    "Website": "http://www.bacalum.com",
    "Sector": "MAINTENNANCE AND REPAIR",
    "Sub-Sector": "INSTALLATION, AND FIXING OF ALUMINUM WINDOWS AND DOORS/ ALUMINUM WORKS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "B-&-C-logo.jpg"
  },
  {
    "Account Number": 303396,
    "Account Name": "BULE ELECTRICAL MATERIALS",
    "Profile": "",
    "Tel": "0114432341/42/0114450251",
    "Mobile": "0911204722",
    "Email": "bule@ethionet.et",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "SOLAR ENERGY EQUIPMENTS AND ELECTRICAL EQUIPMENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "bulae-logo.jpg"
  },
  {
    "Account Number": 303396,
    "Account Name": "BULE ELECTRICAL MATERIALS",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911204722",
    "Email": "bule@ethionet.et",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "ELECTRICAL AND WIRING ACCESSORIES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "bulae-logo.jpg"
  },
  {
    "Account Number": 1502211,
    "Account Name": "IMPRESSION GENERAL TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911673724/0911805895",
    "Email": "derejebedilu@yahoo.com",
    "Website": "",
    "Sector": "EXPORT",
    "Sub-Sector": "PULSES/CEREALS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "Imperssion copy.png",
    "Video": "impertion.gif",
    "logo": "imperssion-general-trading-logo.jpg"
  },
  {
    "Account Number": 1502211,
    "Account Name": "IMPRESSION GENERAL TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911673724/0911805895",
    "Email": "derejebedilu@yahoo.com",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "ELECTRICITY",
    "status": "Member",
    "Category": "business",
    "Is-adv": "False",
    "Image": "Imperssion copy.png",
    "Video": "impertion.gif",
    "logo": "imperssion-general-trading-logo.jpg"
  },
  {
    "Account Number": 1502211,
    "Account Name": "IMPRESSION GENERAL TRADING PLC",
    "Profile": "",
    "Tel": "0118495213",
    "Mobile": "0911673724/0911805895",
    "Email": "derejebedilu@yahoo.com",
    "Website": "",
    "Sector": "EXPORT",
    "Sub-Sector": "OILSEEDS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "False",
    "Image": "Imperssion copy.png",
    "Video": "impertion.gif",
    "logo": "imperssion-general-trading-logo.jpg"
  },
  {
    "Account Number": 1510206,
    "Account Name": "ZIAD MOHAMED IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0915330617/0915320900",
    "Email": "info.ziadimportexport@gmail.com",
    "Website": "",
    "Sector": "EXPORT",
    "Sub-Sector": "COFFEE AND TEA",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Ziad mohammed.gif",
    "logo": "ZID-logo.jpg"
  },
  {
    "Account Number": 1510206,
    "Account Name": "ZIAD MOHAMED IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0915330617/0915320900",
    "Email": "info.ziadimportexport@gmail.com",
    "Website": "",
    "Sector": "EXPORT",
    "Sub-Sector": "BEVERAGE CROPS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Ziad mohammed.gif",
    "logo": "ZID-logo.jpg"
  },
  {
    "Account Number": 1510206,
    "Account Name": "ZIAD MOHAMED IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0915330617/0915320900",
    "Email": "info.ziadimportexport@gmail.com",
    "Website": "",
    "Sector": "EXPORT",
    "Sub-Sector": "COFFEE AND TEA",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Ziad mohammed.gif",
    "logo": "ZID-logo.jpg"
  },
  {
    "Account Number": 1510206,
    "Account Name": "ZIAD MOHAMED IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0915330617/0915320900",
    "Email": "info.ziadimportexport@gmail.com",
    "Website": "",
    "Sector": "EXPORT",
    "Sub-Sector": "BEVERAGE CROPS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Ziad mohammed.gif",
    "logo": "ZID-logo.jpg"
  },
  {
    "Account Number": 1506161,
    "Account Name": "MTT CONSULTING ARCHITECHTS AND ENGINEERING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911208427",
    "Email": "mtt.cae@gmail.com",
    "Website": "",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "CONSULTING ENGINEERS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "mtt.gif",
    "logo": "MTT-logo.jpg"
  },
  {
    "Account Number": 1504392,
    "Account Name": "HAVERIM CONSTRUCTION",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911516233",
    "Email": "haverimcon@gmail.com",
    "Website": "http://www.haverim.com",
    "Sector": "CONSTRUCTION",
    "Sub-Sector": "GENERAL CONTRACTOR",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "haverim.gif",
    "logo": "haverim.jpg"
  },
  {
    "Account Number": 1500943,
    "Account Name": "JIGRA INTERNATIONAL BUSINESS PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911515123/0911526540/41/42/0930848484",
    "Email": "jigrachem@gmail.com",
    "Website": "http://jigragroup.com",
    "Sector": "IMPORT",
    "Sub-Sector": "PLASTICS IN PRIMARY FORMS AND NON-PRIMARY FORMS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Jigra.gif",
    "logo": "jigra1.jpg"
  },
  {
    "Account Number": 1500943,
    "Account Name": "JIGRA INTERNATIONAL BUSINESS PLC",
    "Profile": "",
    "Tel": "0116629953/54",
    "Mobile": "0911515123/0911526540/41/42/0930848484",
    "Email": "jigrachem@gmail.com",
    "Website": "http://jigragroup.com",
    "Sector": "IMPORT",
    "Sub-Sector": "BASIC INDUSTRIAL CHEMICALS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Jigra.gif",
    "logo": "jigra1.jpg"
  },
  {
    "Account Number": 1500943,
    "Account Name": "JIGRA INTERNATIONAL BUSINESS PLC",
    "Profile": "",
    "Tel": "0115585384",
    "Mobile": "0911515123/0911526540/41/42/0930848484",
    "Email": "jigrachem@gmail.com",
    "Website": "http://jigragroup.com",
    "Sector": "IMPORT",
    "Sub-Sector": "DYEING, TANNING AND COLORING MATERIALS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Jigra.gif",
    "logo": "jigra1.jpg"
  },
  {
    "Account Number": 1500943,
    "Account Name": "JIGRA INTERNATIONAL BUSINESS PLC",
    "Profile": "",
    "Tel": "0115585384",
    "Mobile": "0911515123/0911526540/41/42/0930848484",
    "Email": "jigrachem@gmail.com",
    "Website": "http://jigragroup.com",
    "Sector": "IMPORT",
    "Sub-Sector": "CHEMICALS AND CHEMICAL PRODUCTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Jigra.gif",
    "logo": "jigra1.jpg"
  },
  {
    "Account Number": 1500943,
    "Account Name": "JIGRA INTERNATIONAL BUSINESS PLC",
    "Profile": "",
    "Tel": "0116639643",
    "Mobile": "0911515123/0911526540/41/42/0930848484",
    "Email": "jigrachem@gmail.com",
    "Website": "http://jigragroup.com",
    "Sector": "IMPORT",
    "Sub-Sector": "FOREIGN TRADE AGENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Jigra.gif",
    "logo": "jigra1.jpg"
  },
  {
    "Account Number": 1500943,
    "Account Name": "JIGRA INTERNATIONAL BUSINESS PLC",
    "Profile": "",
    "Tel": "0116639643",
    "Mobile": "0911515123/0911526540/41/42/0930848484",
    "Email": "jigrachem@gmail.com",
    "Website": "http://jigragroup.com",
    "Sector": "IMPORT",
    "Sub-Sector": "PETRO CHEMICAL PRODUCTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Jigra.gif",
    "logo": "jigra1.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "EXPORT",
    "Sub-Sector": "PEPPER AND SPICES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "EXPORT",
    "Sub-Sector": "FRUITS & VEGETABLES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "TRANSPORT, STORAGE AND COMMUNICATION",
    "Sub-Sector": "CUSTOMS CLEARANCE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "DEVELOPING REAL ESTATE, SUBDIVIDING REAL ESTATE INTO LOTS AND RESIDENTIAL DEVELOPMENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "MANUFACTURING OF MOTORCYCLES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "IMPORT",
    "Sub-Sector": "INDUSTRIAL, AGRICULTURAL AND CONSTRUCTION MACHINERIES AND OTHER RELATED WORKS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "EXPORT",
    "Sub-Sector": "OILSEEDS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "EXPORT",
    "Sub-Sector": "PULSES/CEREALS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 1509241,
    "Account Name": "EL AUTO ENGINEERING AND TRADING PLC",
    "Profile": "",
    "Tel": "0116673176",
    "Mobile": "0930033303/0905000009",
    "Email": "ceo@elautoas.com",
    "Website": "http://www.elautoas.com",
    "Sector": "EXPORT",
    "Sub-Sector": "CUT FLOWERS AND PLANTS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ELATO.gif.gif",
    "logo": "Eleto-engineering.jpg"
  },
  {
    "Account Number": 904344,
    "Account Name": "ERMIAS ADVERTISING AND PRINTING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911218383/0911240200",
    "Email": "ermias.e24@gmail.com",
    "Website": "",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "ADVERTISING",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ermias.gif",
    "logo": "ermias-advertising.jpg"
  },
  {
    "Account Number": 1509599,
    "Account Name": "MIRKA MOTORS MANUFACTURING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911217451/0931313130",
    "Email": "ikramautosolution@gmail.com",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "INDUSTRIAL, AGRICULTURAL AND CONSTRUCTION MACHINERIES AND OTHER RELATED WORKS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "IKRAM.gif.gif",
    "logo": "IKRAM-MOTORS-LOGO.jpg"
  },
  {
    "Account Number": 1509599,
    "Account Name": "MIRKA MOTORS MANUFACTURING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911217451/0931313130",
    "Email": "ikramautosolution@gmail.com",
    "Website": "",
    "Sector": "MAINTENNANCE AND REPAIR",
    "Sub-Sector": "MULTI PURPOSE VEHICLES AND PARTS MAINTENANCE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "IKRAM.gif.gif",
    "logo": "IKRAM-MOTORS-LOGO.jpg"
  },
  {
    "Account Number": 1509599,
    "Account Name": "MIRKA MOTORS MANUFACTURING AND TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911217451/0931313130",
    "Email": "ikramautosolution@gmail.com",
    "Website": "",
    "Sector": "COMMUNITY, SOCIAL AND PERSONAL SERVICES",
    "Sub-Sector": "MEDIA ENTERTAINMENT PRODUCTION AND DISTRIBUTION",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "IKRAM.gif.gif",
    "logo": "IKRAM-MOTORS-LOGO.jpg"
  },
  {
    "Account Number": 103721,
    "Account Name": "ABBAHWA TRADING P.L.C",
    "Profile": "",
    "Tel": "0114403355/0114403356",
    "Mobile": "0930034987",
    "Email": "abbahawaimport@gmail.com",
    "Website": "http://www.abbahawa.com",
    "Sector": "EXPORT",
    "Sub-Sector": "COFFEE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "Abahawa.gif (1).gif",
    "logo": "abahawa-logo.jpg"
  },
  {
    "Account Number": 1200420,
    "Account Name": "OROMIA COFFEE FARMERS COOPERATIVE SOLICTIES UNION",
    "Profile": "",
    "Tel": "0114654433/0114391262",
    "Mobile": "0929905786/0911226744/0911234332/0909921568",
    "Email": "coffunion@gmail.com",
    "Website": "http://www.oromiacoffeeunion.org",
    "Sector": "EXPORT",
    "Sub-Sector": "COFFEE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "ONEKOO (3).gif.gif",
    "logo": "ONE-KOO.jpg"
  },
  {
    "Account Number": 1509342,
    "Account Name": "SOAL IMPORT AND EXPORT",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911238221",
    "Email": "soalimportandexport@gmail.com",
    "Website": "http://www.soalbusiness.com",
    "Sector": "EXPORT",
    "Sub-Sector": "COFFEE AND TEA",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "soal-last-edited.jpg"
  },
  {
    "Account Number": "",
    "Account Name": "Esdros construction, Trade and\n industry s.c",
    "Profile": "",
    "Tel": "0111 57 98 63/0111575954",
    "Mobile": "",
    "Email": "info@esdros.com",
    "Website": "",
    "Sector": "CONSTRUCTION",
    "Sub-Sector": "",
    "status": "Not-Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "ESDROS.jpg"
  },
  {
    "Account Number": "",
    "Account Name": "OROMIA INDUSTRIAL PARK",
    "Profile": "",
    "Tel": "",
    "Mobile": "",
    "Email": "",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "",
    "status": "Not-Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "oromiya industrial copy.png",
    "Video": "OROMIYA.gif.gif",
    "logo": "Oromiya-industrial-logo.jpg"
  },
  {
    "Account Number": 1508853,
    "Account Name": "BEKI TRADING PLC",
    "Profile": "",
    "Tel": "0116677546",
    "Mobile": "0911240959",
    "Email": "bekitradingplc@gmail.com",
    "Website": "http://bekitradingplc.com",
    "Sector": "EXPORT",
    "Sub-Sector": "PULSES",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "12.jpg",
    "Video": "Beki trading (3).gif (1).gif",
    "logo": "beki-trading-logo.jpg"
  },
  {
    "Account Number": 1508853,
    "Account Name": "BEKI TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911240959",
    "Email": "bekitradingplc@gmail.com",
    "Website": "http://bekitradingplc.com",
    "Sector": "IMPORT",
    "Sub-Sector": "METAL ,NON METALS, METAL ORES AND SCRAPS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "12.jpg",
    "Video": "Beki trading (3).gif (1).gif",
    "logo": "beki-trading-logo.jpg"
  },
  {
    "Account Number": 1508853,
    "Account Name": "BEKI TRADING PLC",
    "Profile": "",
    "Tel": "",
    "Mobile": "0911240959",
    "Email": "bekitradingplc@gmail.com",
    "Website": "http://bekitradingplc.com",
    "Sector": "EXPORT",
    "Sub-Sector": "OILSEEDS",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "12.jpg",
    "Video": "Beki trading (3).gif (1).gif",
    "logo": "beki-trading-logo.jpg"
  },
  {
    "Account Number": "",
    "Account Name": "BULUKO TEXTILE",
    "Profile": "",
    "Tel": "",
    "Mobile": "",
    "Email": "",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "",
    "status": "Not-Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "bulko last and final copy.png",
    "Video": "Buluko (3).gif.gif",
    "logo": "bulko-logo-final.jpg"
  },
  {
    "Account Number": 1507873,
    "Account Name": "ALEMU SUPLIMENTARY FOOD PROCESING AND SALES PRIVATE ENTERPRISE",
    "Profile": "",
    "Tel": "0115573865",
    "Mobile": "0938650746/0929341737",
    "Email": "mealfancheyigen@gmail.com",
    "Website": "",
    "Sector": "MANUFACTURING",
    "Sub-Sector": "SPICES,CONDIMENTS,VBINGAR,YEAST,EGG PRODUCE SOUPS AND OTHER FOOD PRODUCT.",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "alemu-logo-Recovered.jpg"
  },
  {
    "Account Number": 1508252,
    "Account Name": "RSM CONSULTING PLC",
    "Profile": "",
    "Tel": "0118350883",
    "Mobile": "0911340014",
    "Email": "shehir8@gmail.com",
    "Website": "",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "CONSULTANCY SERVICE FOR TAX AND FINANCE",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "RSM-logo.jpg"
  },
  {
    "Account Number": 1508252,
    "Account Name": "RSM CONSULTING PLC",
    "Profile": "",
    "Tel": "0118350883",
    "Mobile": "0911340014",
    "Email": "shehir8@gmail.com",
    "Website": "",
    "Sector": "REAL ESTATE AND BUSINESS SERVICE",
    "Sub-Sector": "CONSULTANCY SERVICE FOR INVESTMENT",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "",
    "Video": "",
    "logo": "RSM-logo.jpg"
  },
  {
    "Account Number": 100003,
    "Account Name": "ETHIOPIAN SPRING M.B. S.C.",
    "Profile": "",
    "Tel": "0114402254/4400088/4403632",
    "Mobile": "0911873394",
    "Email": "arg262000@yahoo.com",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "IRON AND STEEL",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "ethiopian spring final quarter copy.png",
    "Video": "",
    "logo": ""
  },
  {
    "Account Number": 100003,
    "Account Name": "ETHIOPIAN SPRING M.B. S.C.",
    "Profile": "",
    "Tel": "0114402254/4400088/4403632",
    "Mobile": "0911873394",
    "Email": "arg262000@yahoo.com",
    "Website": "",
    "Sector": "IMPORT",
    "Sub-Sector": "IRON AND STEEL",
    "status": "Member",
    "Category": "business",
    "Is-adv": "True",
    "Image": "ethiopian spring final quarter copy.png",
    "Video": "",
    "logo": ""
  },

      ] ;
      // Define a map for filtering logic by index
      filteredBusinesses = offLineData.where((element) => element["logo"]!="").toList();
      // filteredBusinesses = offLineData;

      // print(widget.index);
    

   //avoiding duplicated adv from the list based on Account Name column
    // Set<dynamic> uniqueBusinesses = filteredBusinesses.toSet();
  //  filteredBusinesses = uniqueBusinesses.toList();

Set<String> seenKeys = {}; // Set to store unique combinations of relevant keys

for (final element in filteredBusinesses) {
  // Define the key(s) to compare for uniqueness (e.g., "name" and "age")
  final keyCombination = "${element["Account Name"]}"; 

  if (!seenKeys.contains(keyCombination)) {
    seenKeys.add(keyCombination);
    uniqueBusinesses.add(element);
  }
}
      setState(() {
        isLoading = false;
      });
    } on FirebaseException catch (e) {
      setState(() {
        isLoading = false;
        errorMessage = 'Error: ${e.message}';
      });
      print('Error fetching data: ${e.code} - ${e.message}');
    } catch (e) {
      // Handle other potential errors
      setState(() {
        isLoading = false;
        errorMessage = 'An error occurred.';
      });
      print('Error fetching data: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            if (isLoading)
              const CircularProgressIndicator(),
            if (errorMessage.isNotEmpty)
              Text(errorMessage),
            if (!isLoading && errorMessage.isEmpty)
              _buildGridView(),
          ],
        ),
      ),
    );
  }

  Widget _buildGridView() {
  return SizedBox(
    height: 200,
    child: GridView.builder(
scrollDirection: Axis.horizontal,
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2, // Change to adjust the number of columns
        crossAxisSpacing: 10.0, // Spacing between columns
        mainAxisSpacing: 10.0, // Spacing between rows
        childAspectRatio: 1.2, // Adjust aspect ratio for desired layout
      ),
      itemCount: uniqueBusinesses.length,
      itemBuilder: (context, index) {
        final Map<dynamic, dynamic> businessData = uniqueBusinesses[index];
        final String icon = businessData['logo'].toString();
        Future<String> imageUrlFuture = storeImageInFirebase(icon);
        final String name = businessData["Account Name"].toString();

        return GestureDetector(
          onTap: () => Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => CompanyDescription(detail: businessData)),
          ),
          child: Column(
            children: [
              Container(
                width: 60.0,
                height: 60.0,
                decoration: const BoxDecoration(
                  color: Colors.white,
                  // border: Border.all(
                  //   color: Color.fromARGB(255, 229, 234, 232),
                  // ),
                  // ... other decoration for the container
                ),
                child: FutureBuilder<String>(
                  future: imageUrlFuture,
                  builder: (context, snapshot) {
                    if (snapshot.hasData) {
                      return Image.network(snapshot.data!);
                    } else if (snapshot.hasError) {
                      return Text('Error: ${snapshot.error}');
                    } else {
                      return Text('');
                      // CircularProgressIndicator();
                    }
                  },
                ),
              ),
              // SizedBox(width: 20.0),
              Padding(
                padding: const EdgeInsets.only(top: 8.0),
                child: Text(
                  name,
                  style: TextStyle(fontSize: 12),
                  textAlign: TextAlign.left,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
            ],
          ),
        );
      },
    ),
  );
}

  Future<String> storeImageInFirebase(String fileName) async {
    try {
      final storage = FirebaseStorage.instance.ref();
      final images = storage.child('logo');
      final imageRef = images.child(fileName);

      final networkImageUrl = await imageRef.getDownloadURL();
      // print(networkImageUrl);
      return networkImageUrl;
    } on FirebaseException catch (e) {
      // Handle potential errors
      print('Error storing image: ${e.code} - ${e.message}');
      return ''; // Or throw an exception for further handling
    }
  }
}

